name: Pleun
title: Portfolio - Pleun
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Over
    url: "{{ site.baseurl }}/over"
  - title: Frontend
    url: "{{ site.baseurl }}/frontend"
  - title: Grafisch
    url: "{{ site.baseurl }}/grafisch"
  - title: Muziek
    url: "{{ site.baseurl }}/muziek"
  - title: Contact
    url: "{{ site.baseurl }}/contact"
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
